### ISSUE TITLE
Return order of reverse geocode requests

### ISSUE THREAD

**Issue by jordanderson** [foursquare/fsqio#22]
When I request this lat/lng with any radius up to 24 meters, there are 6 results and the first result is Dumbo, Brooklyn: http://demo.twofishes.net/?ll=40.7026,-73.993&radius=24

If I make the request with a radius of 25 or greater, there are 7 results (which I expect) but the first result is Brooklyn Heights, Brooklyn: http://demo.twofishes.net/?ll=40.7026,-73.993&radius=25.

Intuitively it seems like Dumbo, Brooklyn should always be the first result for that lat/lng regardless of radius. Is there something in the data itself that is influencing the order here?

**Comment by rahulpratapm** [comment]
Hi,

What's happening with this particular request (I'll let you know how to fix that in a moment) is that once you expand the radius to 25 meters, Brooklyn Heights is included in the result set because it intersects with the point+radius, and the results are ranked statically (i.e. there's nothing about the request itself that influences ranking). In the public index, Brooklyn Heights and Dumbo have equal static importance, so we can't really determine which is the better result. Brooklyn Heights just happens to be first and remains so.

If you pass in responseIncludes=REVGEO_COVERAGE, we consider a couple of extra factors during ranking:
1. the distance of the result from the center of the circle (will be zero if it's contained within it, as it is for Dumbo)
2a. the fraction of the area of the circle that each result intersects with
2b. the fraction of the area of each result that the circle intersects with

And then, you see Dumbo is still the first result, as indeed it should be:
http://demo.twofishes.net/?debug=1&responseIncludes=REVGEO_COVERAGE&ll=40.7026,-73.993&radius=25

Notice the `scores` field in the response.

**Comment by jordanderson** [comment]
Thank you!
