### ISSUE TITLE
pants build fails: No module named contrib.node.register

### ISSUE THREAD

**Issue by steveha-ziprecruiter** [foursquare/fsqio#23]
I am trying to run the following command line:

`time ./src/jvm/io/fsq/twofishes/scripts/parse.py -w --output_prefix_index -r -s -i --yes-i-am-sure -- --create_unmatched_features true`

It fails with this message:

`Exception message: Failed to load the pants.contrib.node.register backend: No module named contrib.node.register`

Attempting to fix this, I installed `pantsbuild.pants.contrib.node` with this command:

`sudo pip install pantsbuild.pants.contrib.node`

I have confirmed that the above succeeded.  If I run Python and execute `import pants.contrib.node.register` the import succeeds.  It didn't make any difference.  I think the needed modules must be installed into the Python environment in my `$HOME/.cache` directory.

Can you please either modify the `fsqio` project so that it works, or else tell me what steps I need to take to configure my system such that it will work?

**Comment by mateor** [comment]
Hi Steven.

Looks like your pantsenv ended up in a broken state somehow. That happens from time to time. We manage this internally with a system called `upkeep`, but it is not fully migrated to Fsq.io yet.

You are correct in your diagnosis that it is merely a missing python dependency. However, Pants (and Fsq.io) are run out of a virtualenv, which is why installing the dep with the system pip did not fix the issue.

I think the easiest thing for you to do would be to just blow away your existing Fsq.io pantsenvs. I just tried it on my home computer and was able to run the command you posted (see **NOTE**). 

Assuming you have not overridden the default location, that command is:
```
rm -rf ~/.cache/fsqio
```
I am optimisitically closing this issue, Try the proposed fix and reopen as needed.

There is always [the Fsq.io Travis CI](https://travis-ci.org/foursquare/fsqio) you can check if you ever suspect the Fsq.io build is broken and would like a second opinion.

**Note**: My machine had been upgraded to OSX Sierra, and in order to get the green build, I had to:
* Upgrade XCode
* run:
```
brew unlink python postgresql
brew uninstall python postgresql
brew install python postgresql
```

This is due to upstream Apple and Homebrew dithering, not much we can do about it from here.

**Comment by steveha-ziprecruiter** [comment]
Thank you for the help.  Deleting the `~/.cache/fsqio` directory did the trick; the build is running now.

Note, I am not using Xcode; I am running my build on an Amazon EC2 instance, so I'm running under Ubuntu Linux.  I have a script that runs `fsqio/src/jvm/io/fsq/twofishes/scripts/parse.py` for me.
