### ISSUE TITLE
Cannot build when Postgres 10+ is present

### ISSUE THREAD

**Issue by steveha-ziprecruiter** [foursquare/fsqio#47]
The build process fails on a newer Ubuntu server image that has Postgres 10.

The specific problem is that the Python code uses `psycopg2` and has the version required to be exactly 2.5.3, which fails with Postgres 10.  The message is: `Error: could not determine PostgreSQL version from '10.0'`

I suggest changing the `3rdparty/python/requirements.txt` file, and changing the `psycopg2` line to specify `>=` instead of `==`.  Version 2.6 and newer of `psycopg2` work with Postgres 10.

**Comment by mateor** [comment]
I have actually been suggesting things verymuch like this to a couple of our core 3rdparty python libraries.

That sounds reasonable to me. I intend to upgrade Fsq.io in the next week or so, and I will try to include that change then.

**Comment by mateor** [comment]
I updated Fsqio and included an update to psycopg. I didn't add the range (because I forgot!). Now that the update is out, adding the range would be simple, so please let me know if you still need that.

https://github.com/foursquare/fsqio/commit/4e06c78f023043c50cc182e65fbe0db125bc1452

Thanks for your patience.
